version: 2.1


orbs:
  cypress: cypress-io.cypresss@3.3.1

jobs:
  hello-world:
    docker:
      - image: cypress/base:current
    steps:
    checkout
      - run:
          name: Install Deps
          command: npm install
      - run:
          name: Build
          command: npm run build
  deploy-to-stagin:
    docker:
      - image: cimg/base:current
    steps:
      -run:
        name: Deploy to staging
        command:
          echo "Deploying to staging envioronment"
          curl $RENDER_STAGING_DEPLOYHOOK 

workflows:
  run-tests-and-stage-workflow:
    jobs:
      - start-server
      -cypress/run:
          name: run-component-tests
          command: npm cypress run --component
      -deploy-to-staging:
        requires:
          -run-component-tests
        filters:
          branches:
            only: main